spring:
  application:
    name: code-flow

  datasource:
    url: jdbc:postgresql://localhost:5443/codeflow
    username: codeflow
    password: codeflow
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate          # Flyway cuida do schema
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt:
    secret: ${JWT_SECRET:change-me-in-development-only}
    expiration-ms: 604800000     # 7d em ms

server:
  port: ${PORT:3010}