CREATE TABLE onboarding_whatsapp_numbers (
    id BIGSERIAL PRIMARY KEY,
    label VARCHAR(100),
    phone VARCHAR(15) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);